{% set name = "radio-beam" %}
{% set version = "0.3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: d2214fb5f404016e8adcdf91fc3a2f556bd779ea4f9f38b872b0be712b47276a

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=61.2
    - setuptools_scm
  run:
    - python
    - astropy >=6.1
    - numpy >=1.24
    - scipy >=1.8
    - packaging >=19
    - setuptools >=62.3.3
    - matplotlib-base >=3.5

test:
  imports:
    - radio_beam
  requires:
    - pip
    - pytest
    - pytest-astropy >=0.10
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs radio_beam.tests

about:
  home: https://github.com/radio-astro-tools/radio-beam
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for Beam I/O and Manipulation
  description: |
    Radio Beam is a simple toolkit for reading beam information from FITS headers and manipulating beams
  doc-url: https://radio-beam.readthedocs.io/en/latest
  dev-url: https://github.com/radio-astro-tools/radio-beam

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - keflavich
